### ISSUE TITLE
Invalid call of CompoundProcessor::processPtiContentObjectData

### ISSUE THREAD

**Issue by hirnschmalz** [SomeBdyElse/typo3-pti#30]
@SomeBdyElse in version 4.0.4 you added a new argument to the call of processPtiContentObjectData without modifying the method signature

https://github.com/SomeBdyElse/typo3-pti/blob/d225a65e96a69be38179ed6db6cdde216ec35c5b/Classes/Processor/CompoundProcessor.php#L124

As far as I can tell the `$processorConfiguration` should not be added as an argument here.

**Comment by SomeBdyElse** [comment]
Hi @hirnschmalz ! Thank you for reporting! I released a new version v4.0.5 with a fix.
